[package]
name = "rhasher"
version = "0.1.0"
authors = ["user"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crc32fast = "1.2.1"
crc64fast = "1.0.0"
rust-crypto = "^0.2"